Famille_DO/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.accueil, name='accueil'),
    path('diasomonte/', admin.site.urls),
    path('accueil/', views.accueil, name='accueil'),
    path('restaurants/', include('RESTAURANTS.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

RESTAURANTS/urls.py
#from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'RESTAURANTS'
urlpatterns = [
    path('', views.restaurants, name='restaurants'),
    path('details/<int:resto_id>/', views.details, name='details'),
    path('search/', views.recherche, name='recherche'),
]

RESTAURANTS/models.py
from django.db import models


class Restaurant(models.Model):
    name = models.CharField('Nom', max_length=100, blank=False)
    email = models.EmailField(max_length=150, blank=True)
    adresse = models.CharField(max_length=200, blank=False)
    codePostal = models.BigIntegerField(default=68100, blank=False)
    ville = models.CharField(max_length=200, default="Mulhouse", blank=False)
    phone = models.CharField('téléphone', max_length=15, blank=True)
    website = models.URLField('site web', blank=True)
    available = models.BooleanField('disponnible', default=True)
    image = models.URLField("image", blank=True)

    def __str__(self):
        return self.name

Famille_DO/views.py
from django.shortcuts import render


def accueil(request):
    return render(request, 'Famille_DO/accueil.html')

RESTAURANTS/views.py
from django.shortcuts import render, get_object_or_404
from .models import Restaurant
from django.core.paginator import Paginator


def restaurants(request):
    restos = Restaurant.objects.filter(available=True).order_by('name')
    paginator = Paginator(restos, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'RESTAURANTS/restaurants.html', context)


def details(request, resto_id):
    resto = get_object_or_404(Restaurant, pk=resto_id)
    context = {'resto': resto}
    return render(request, 'RESTAURANTS/details.html', context)


def recherche(request):
    query = request.GET.get('query')
    if not query:
        restos = Restaurant.objects.all().order_by('name')
    else:
        # title contains the query is and query is not sensitive to case.
        restos = Restaurant.objects.filter(name__icontains=query).order_by('name')
    if not restos.exists():
        restos = Restaurant.objects.filter(ville__icontains=query).order_by('name')
    if not restos.exists():
        restos = Restaurant.objects.filter(codePostal__icontains=query).order_by('name')
    results = "Résultats pour la requête < %s >" % query

    paginator = Paginator(restos, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'results': results
    }
    return render(request, 'RESTAURANTS/recherche.html', context)

RESTAURANTS/templates/RESTAURANTS/details.html
{% extends 'layout/head.html' %}
{% block title %}DETAILS{% endblock %}
{% load static %}
{% block breadcrumb %}
		<nav aria-label="breadcrumb">
  			<ol class="breadcrumb">
    			<li class="breadcrumb-item"><a class = "lien" href="{% url 'accueil' %}">Accueil</a></li>
				<li class="breadcrumb-item"><a class="lien" href="{% url 'RESTAURANTS:restaurants' %}">RESTAURANTS</a></li>
    			<li class="breadcrumb-item active">DETAILS</li>
				<li class="breadcrumb-item active">{{ resto.name }}</li>
  			</ol>
		</nav>
		{% endblock %}
{% block body %}
	{% include 'RESTAURANTS/recherche_form.html' %}
	<div class="tableau">
		<h2>{{ resto.name }}</h2>
	</div>
	<div class="btn table-primary bouton_details tableau1">
		<img class="resto-img" src="{{ resto.image }}" width="100%" height="100%">
	</div>
	<br>
	<div>
		<h4>{{ resto.adresse }} {{ resto.codePostal }} {{ resto.ville }}</h4>
	</div>
	<div>
		<h4><a href="{{ resto.website }}" target="_blank">{{ resto.website }}</a></h4>
	</div>
	<div>
		<h4><a href="mailto:{{ resto.email }}">{{ resto.email }}</a></h4>
	</div>
	<div class="tableau2">
		<h4><a href="tel:{{ resto.phone }}">{{ resto.phone }}</a></h4>
	</div>
{% endblock %}

RESTAURANTS/templates/RESTAURANTS/pagination.html
{% load static %}
<<div class="pagination">
    <span class="step-links tableau5">
        <span class="tableau5">
            {% if page_obj.has_previous %}
                <a href="?page=1"><button class="btn btn-primary bouton-pagination">&laquo; premi&egrave;re</button></a>
            <a href="?page={{ page_obj.previous_page_number }}"><button class="btn btn-primary bouton-pagination">< pr&eacute;c&eacute;dante</button></a>
            {% endif %}
        </span>

        <span class="current tableau5">
            <span class="page-bouton">Page {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}</span>
        </span>

        <span class="tableau5">
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"><button class="btn btn-primary bouton-pagination">suivante ></button></a>
            <a href="?page={{ page_obj.paginator.num_pages }}"><button class="btn btn-primary bouton-pagination">derni&egrave;re &raquo;</button></a>
            {% endif %}
        </span>
    </span>
</div>

RESTAURANTS/templates/RESTAURANTS/recherche.html
{% extends 'layout/head.html' %}
{% block title %}RECHERCHE{% endblock %}
{% load static %}
{% block breadcrumb %}
		<nav aria-label="breadcrumb">
  			<ol class="breadcrumb">
    			<li class="breadcrumb-item"><a class = "lien" href="{% url 'accueil' %}">Accueil</a></li>
				<li class="breadcrumb-item"><a class="lien" href="{% url 'RESTAURANTS:restaurants' %}">RESTAURANTS</a></li>
    			<li class="breadcrumb-item active">RECHERCHE</li>
  			</ol>
		</nav>
		{% endblock %}
{% block body %}
{% include 'RESTAURANTS/recherche_form.html' %}
	<center><h4>{{ results }}</h4></center>
	{% for resto in page_obj %}
	<span>
		<a href="../details/{{resto.id}}">
			<button class="btn table-primary bouton">
				<h2>{{ resto.name }}</h2>
				<div>
					<img class="resto-img img-responsive" src="{{ resto.image }}" width="100%" height="100%">
				</div>
				<br>
				<div>
					<h5><a href="tel:{{ resto.phone }}">{{ resto.phone }}</a></h5>
				</div>
				<div>
					<h4>{{ resto.ville }}</h4>
				</div>
			</button>
		</a>
	</span>
	{% endfor %}

	{% include 'RESTAURANTS/pagination.html' %}
{% endblock %}

RESTAURANTS/templates/RESTAURANTS/recherche_form.html
{% load static %}
<div class="center tableau3">
    <form class="text-center" action="{% url 'RESTAURANTS:recherche' %}" method="get" accept-charset="utf-8">
      <div class="form-group">
          <label for="searchForm"><h3>Chercher un restaurant</h3></label>
          <input id="searchForm" class="form-control" name="query">
          
          <span><button class="btn btn-primary" method="."><h5>Trouvez le restaurant de vos rêves en tapant son nom, ville ou code postal.&nbsp;&nbsp;<i class="fas fa-search"></i></h5></button></span>
      </div>
    </form>
</div>

RESTAURANTS/templates/RESTAURANTS/restaurants.html
{% extends 'layout/head.html' %}
{% block title %}RESTAURANTS{% endblock %}
{% load static %}
{% block breadcrumb %}
		<nav aria-label="breadcrumb">
  			<ol class="breadcrumb">
    			<li class="breadcrumb-item"><a class = "lien" href="{% url 'accueil' %}">Accueil</a></li>
    			<li class="breadcrumb-item active">RESTAURANTS</li>
  			</ol>
		</nav>
		{% endblock %}
{% block body %}
	{% include 'RESTAURANTS/recherche_form.html' %}
	{% for resto in page_obj %}
	<span>
		<a href="details/{{resto.id}}">
			<button class="btn table-primary bouton">
				<h2>{{ resto.name }}</h2>
				<div>
					<img class="resto-img" src="{{ resto.image }}" width="100%" height="100%">
				</div>
				<br>
				<div>
					<h5><a href="tel:{{ resto.phone }}">{{ resto.phone }}</a></h5>
				</div>
				<div>
					<h4>{{ resto.ville }}</h4>
				</div>
			</button>
		</a>
	</span>
	{% endfor %}

	{% include 'RESTAURANTS/pagination.html' %}
	
{% endblock %}

templates/Famille_DO/accueil.html
{% extends 'layout/head.html' %}
{% block title %}ACCUEIL{% endblock %}
{% load static %}
{% block breadcrumb %}
		<nav aria-label="breadcrumb">
  			<ol class="breadcrumb">
    			<li class="breadcrumb-item">Accueil</li>
  			</ol>
		</nav>
{% endblock %}
{% block body %}
	bonjour à tous !
{% endblock %}

templates/layout/head.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
	<head>
		<title>{% block title %}{% endblock %}</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width = device-width, initial-scale = 1.0">
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css">
		<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="{% static 'fichiers/css/styles.css' %}">
		<link rel="shortcut icon" type="image/png" href="{% static 'medias/images/photo_alexandre_petit.png' %}">
		<script src="https://kit.fontawesome.com/8b420c83a1.js" crossorigin="anonymous"></script>
	</head>
	<body class="fond">
		{% include 'layout/menu.html' %}
		{% block breadcrumb %}
		<nav aria-label="breadcrumb">
  			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="{% url 'accueil' %}"><img class = "portrait" src = "{% static 'images/photo_alexandre_petit.png' %}"/></a></li>
    			<li class="breadcrumb-item"><a href="{% url 'accueil' %}">Accueil</a></li>
    			<li class="breadcrumb-item active"><a href="{% url 'RESTAURANTS:restaurants' %}">RESTAURANTS</a></li>
  			</ol>
		</nav>
		{% endblock %}
		{% block body %}{% endblock %}
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	</body>
</html>

templates/layout/menu.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #74D0F1;">
  <a class="nav-link brand accueil" href="{% url 'accueil' %}"><img class="image_menu" src = "{% static 'medias/images/photo_alexandre_petit.png' %}"/><span class="sr-only">(current)</span></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link brand accueil lien" href="{% url 'accueil' %}">ACCUEIL <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link brand lien" href="{% url 'RESTAURANTS:restaurants' %}">RESTAURANTS</a>
      </li>
    </ul>
  </div>
</nav>